### ISSUE TITLE
Validator::required() failed maybe to often

### ISSUE THREAD

**Issue by phil2phil** [arkuuu/simple-validator#1]
What about these cases for unit tests:

* "" => false
* 0 => true
* 0.0 => true
* "0" => true
* NULL => false
* FALSE => false
* array() => thr InvalidArgumentException?

https://github.com/arkuuu/simple-validator/blob/dea761c93cb4dcf46ae44c3d1f3640588d27707a/src/Validator.php#L16

**Comment by arkuuu** [comment]
Thanks, there are several tests missing at the moment. I'll add them as soon as I find time.

> 0 => true
0.0 => true
"0" => true

You think those should return true, meaning they are valid values when "not empty" is required?

> array() => thr InvalidArgumentException?

Sounds ok, as arrays may never be valid values to test.
